version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "vkmanjeshwar"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-m8ogj0khwf6"
s3_prefix = "vkmanjeshwar"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
